"""
Bake the static half of the Kelvara body-map visual.

Two kinds of thing cross into the browser. Numbers come from DAX at query time,
because they change with every slicer. Labels do not change with slicers, so
they are baked here instead. That is not only cheaper, it removes string
escaping from the payload entirely: if DAX only ever emits digits and commas,
there is no way for a dimension member to break out of a JS literal.

The one string that genuinely has to come from DAX is the filter caption, and
that goes through the full seven-step escape chain on the DAX side.

Writes design-assets/runtime.js, which build_dax.py embeds in the measure.
"""
import csv
import io
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
CSV = os.path.join(ROOT, 'data', 'csv')


def read(name):
    with io.open(os.path.join(CSV, name), encoding='utf-8-sig', newline='') as fh:
        return list(csv.DictReader(fh))


def j(obj):
    return json.dumps(obj, separators=(',', ':'), ensure_ascii=False)


# --- dimension lookups -----------------------------------------------------

regions = read('dim_body_region.csv')
REGIONS, SVG_TO_KEY = {}, {}
for r in regions:
    k = int(r['BodyRegionKey'])
    svg = (r.get('SvgId') or '').strip()
    REGIONS[k] = {'name': r['BodyRegion'], 'svg': svg, 'div': r['Division'],
                  'draw': int(r['IsDrawable'])}
    if svg:
        SVG_TO_KEY.setdefault(svg, []).append(k)

SEV = {}
for r in read('dim_severity_class.csv'):
    SEV[int(r['SeverityKey'])] = {
        'name': r['SeverityClass'],
        'rec': int(r['IsRecordable']), 'dart': int(r['IsDart']),
        'lost': int(r['IsLostTime'])}

MECH = {int(r['MechanismKey']): r['Mechanism'] for r in read('dim_mechanism.csv')}

roles = read('dim_job_role.csv')
ROLE_FIELD = 'JobRole' if 'JobRole' in roles[0] else list(roles[0])[1]
ROLE = {int(r['JobRoleKey']): r[ROLE_FIELD] for r in roles}

site_rows = read('dim_site.csv')
SITE = {int(r['SiteKey']): r['SiteName'] for r in site_rows}
# site -> business unit, so the filter bar can offer business unit without
# shipping it on every one of the 1,492 incident rows
SITE_BU = {int(r['SiteKey']): r['BusinessUnit'] for r in site_rows}
BU = sorted({r['BusinessUnit'] for r in site_rows})
SHIFT = {int(r['ShiftKey']): r['Shift'] for r in read('dim_shift.csv')}
WCLASS = {int(r['WorkerClassKey']): r['WorkerClass'] for r in read('dim_worker_class.csv')}

MONTHS = {}
for r in read('dim_date.csv'):
    MONTHS[int(r['YearMonthKey'])] = r['YearMonthLabel']

# --- assemble --------------------------------------------------------------

AI = {}
_ai = os.path.join(HERE, 'ai-baked.json')
if os.path.exists(_ai):
    AI = json.load(io.open(_ai, encoding='utf-8'))

geometry = io.open(os.path.join(HERE, 'body-baked.js'), encoding='utf-8').read()
renderer = io.open(os.path.join(HERE, 'bodymap.src.js'), encoding='utf-8').read()

out = io.StringIO()
out.write('/* Kelvara body-map runtime. Generated by design-assets/build_runtime.py.\n')
out.write('   Geometry + baked dimension labels + renderer. Do not hand-edit. */\n')
out.write(geometry)
out.write('\nvar KV_REGIONS=%s;\n' % j(REGIONS))
out.write('var KV_SVG_TO_KEY=%s;\n' % j(SVG_TO_KEY))
out.write('var KV_SEV=%s;\n' % j(SEV))
out.write('var KV_MECH=%s;\n' % j(MECH))
out.write('var KV_ROLE=%s;\n' % j(ROLE))
out.write('var KV_SITE=%s;\n' % j(SITE))
out.write('var KV_SITE_BU=%s;\n' % j(SITE_BU))
out.write('var KV_BU=%s;\n' % j(BU))
out.write('var KV_SHIFT=%s;\n' % j(SHIFT))
out.write('var KV_WCLASS=%s;\n' % j(WCLASS))
out.write('var KV_MONTHS=%s;\n' % j(MONTHS))
# Model-written explanations, generated once by bake_ai.py and shipped as data.
# This is the only way the model layer can appear in a published report: a key
# placed in a measure is readable by anyone who opens the report, so there is no
# safe way to call an API at render time from inside Power BI.
out.write('var KV_AI=%s;\n' % j(AI))
# The renderer reads these off window, and `var` at top level of the iframe
# document does land on window, but being explicit survives any future wrapper.
out.write('window.BODY_VIEWBOX=BODY_VIEWBOX;window.BODY_SHAPES=BODY_SHAPES;\n')
out.write('window.BODY_LABELS=BODY_LABELS;window.BODY_DETAIL=BODY_DETAIL;'
          'window.BODY_Z=BODY_Z;\n')
out.write('window.KV_REGIONS=KV_REGIONS;window.KV_SVG_TO_KEY=KV_SVG_TO_KEY;'
          'window.KV_SEV=KV_SEV;window.KV_MECH=KV_MECH;window.KV_ROLE=KV_ROLE;'
          'window.KV_SITE=KV_SITE;window.KV_SITE_BU=KV_SITE_BU;window.KV_BU=KV_BU;'
          'window.KV_SHIFT=KV_SHIFT;window.KV_WCLASS=KV_WCLASS;'
          'window.KV_MONTHS=KV_MONTHS;window.KV_AI=KV_AI;\n')
out.write(renderer)

runtime = out.getvalue()
path = os.path.join(HERE, 'runtime.js')
io.open(path, 'w', encoding='utf-8', newline='').write(runtime)

drawable = sum(1 for v in REGIONS.values() if v['draw'])
print('Kelvara runtime')
print('=' * 62)
print('  regions                 %d  (%d drawable, %d svg ids)'
      % (len(REGIONS), drawable, len(SVG_TO_KEY)))
print('  severity classes        %d' % len(SEV))
print('  mechanisms              %d' % len(MECH))
print('  job roles               %d' % len(ROLE))
print('  months                  %d' % len(MONTHS))
print('  baked AI explanations   %d' % len(AI))
print('  geometry                %6d chars' % len(geometry))
print('  renderer                %6d chars' % len(renderer))
print('  runtime.js              %6d chars' % len(runtime))

bad = [k for k, v in REGIONS.items() if v['draw'] and not v['svg']]
assert not bad, 'drawable regions with no SvgId: %s' % bad
assert '"' not in ''.join(v['name'] for v in REGIONS.values()), 'quote in a region name'
print('\nOK. No drawable region is missing an SvgId.')
