"""Inline the shared renderer into one self-contained DAX measure per page.

  python build-measure.py

Writes `../dax/<page>-inline.dax` for every page. Each measure carries the whole
renderer in its own text, so a visual loads nothing from the internet.

One library, four pages
-----------------------
Every page ships the SAME renderer and routes on the `page` field in its
payload. That costs about 27,000 characters per measure, repeated, which is
cheap against a ~2,100,000 ceiling and far better than four diverging copies of
the same CSS and helpers.

Why inline instead of a CDN
---------------------------
The CDN route is right when several reports share one renderer and you want to
ship a fix by moving a tag. It costs a public repository, a jsDelivr cache you
cannot purge on demand, and a visual that renders blank the day the CDN is
unreachable. Inlining trades that for a measure that is completely
self-contained.

Escaping
--------
Only one transformation is needed for the library text, because it is emitted
inside a DAX string literal:  "  ->  ""

Single quotes, backslashes and angle brackets stay exactly as written: they are
legal in a DAX string and the browser must receive them unchanged. The escape
chain in the repo README applies to DATA being serialised into a JavaScript
literal, which is a different problem from embedding a script body.

The one sequence that cannot appear
-----------------------------------
An HTML parser ends a <script> block at the first case-insensitive `</script`,
wherever it occurs, including inside a JavaScript string. This refuses to build
if one ever appears rather than emitting a measure that truncates halfway and
spills code onto the page.
"""

import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "fincrime-overview.js")
DAXDIR = os.path.join(HERE, "..", "dax")
CEILING = 2100000

# page -> (source dax, measure name)
PAGES = [
    ("guide", "fincrime-guide.dax", "Guide"),
    ("overview", "fincrime-overview.dax", "Financial Crime Overview"),
    ("rules", "fincrime-rules.dax", "Rule Effectiveness"),
    ("risk", "fincrime-risk.dax", "Risk and Exposure"),
]


def library():
    js = io.open(SRC, encoding="utf-8").read()
    if re.search(r"</\s*script", js, re.I):
        raise SystemExit(
            "REFUSED: the renderer contains a closing script tag. Inlined, that "
            "ends the <script> block early and spills the rest onto the page.")
    # Drop the banner: it documents the CDN build and is dead weight in a
    # measure that fetches nothing.
    body = re.sub(r"^/\*!.*?\*/\s*", "", js, flags=re.S)
    return body, body.replace('"', '""')


def main():
    body, lib = library()
    print("renderer %s chars (%s after doubling quotes)"
          % ("{:,}".format(len(body)), "{:,}".format(len(lib))))
    print()

    for page, src, measure in PAGES:
        path = os.path.join(DAXDIR, src)
        if not os.path.exists(path):
            print("  %-9s SKIP (%s missing)" % (page, src))
            continue
        text = io.open(path, encoding="utf-8").read()

        m = re.search(r"^([A-Za-z][A-Za-z ]*) =\s*$(.*?)^RETURN",
                      text, re.S | re.M)
        if not m:
            print("  %-9s SKIP (no measure body)" % page)
            continue
        vars_block = m.group(2).strip("\n")

        header = (
            "// =========================================================================\n"
            "// %s - self-contained, no CDN\n"
            "// -------------------------------------------------------------------------\n"
            "// GENERATED by fincrime/build-measure.py. Do not edit by hand: change\n"
            "// fincrime/fincrime-overview.js or dax/%s and rebuild.\n"
            "//\n"
            "// Drop on an HTML Content visual, STANDARD edition (id ends D3A6855).\n"
            "// The certified lite edition ends D3A6865, strips script tags, and\n"
            "// renders a blank box with no error.\n"
            "// =========================================================================\n\n"
            "%s =\n" % (measure, src, measure))

        out = (header + vars_block + '\n\nVAR Lib = "' + lib + '"\n\n'
               + "RETURN\n"
                 "    \"<div id='fco-root'></div>\"\n"
                 "        & \"<script>\" & Payload\n"
                 "        & \"if(window.FCO&&window.FCO.render){window.FCO.render();}\"\n"
                 "        & \"</script>\"\n"
                 "        & \"<script>\" & Lib & \"</script>\"\n")

        dst = os.path.join(DAXDIR, page + "-inline.dax")
        io.open(dst, "w", encoding="utf-8", newline="").write(out)
        pctv = len(out) / float(CEILING) * 100
        print("  %-9s %-28s %9s chars  %4.1f%% of ceiling"
              % (page, measure, "{:,}".format(len(out)), pctv))
        if pctv > 80:
            print("            WARNING: over 80%% of the ceiling")
    print()
    print("wrote %d measures to %s" % (len(PAGES), os.path.normpath(DAXDIR)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
